"""Task Service Module.

Connects the Task Router with the Model Registry to orchestrate end-to-end
request classification and model inference execution.
"""

from pathlib import Path
from typing import Any, Dict, Optional, Union

from backend.app.models.registry import get_model_for_category
from backend.app.router.task_router import classify_task


def process_task(prompt: str, config_path: Optional[Union[str, Path]] = None) -> Dict[str, Any]:
    """Process a user prompt end-to-end:

    1. Classifies the prompt into a task category (coding, vision, document, general).
    2. Retrieves the configured model engine for that category.
    3. Generates the response from the model.
    4. Returns a dictionary containing the detected category, generated response,
       model name, and backend.

    Args:
        prompt: The raw user prompt or query.
        config_path: Optional path to an alternative models.yaml configuration file.

    Returns:
        Dictionary containing:
        - 'category': The detected task category (e.g. 'coding')
        - 'response': The response text generated by the model
        - 'model_name': Name of the model used (e.g. 'granite')
        - 'backend': Backend runtime used (e.g. 'llama.cpp')
    """
    # Step 1: Classify task category from prompt
    category = classify_task(prompt)

    # Step 2: Retrieve the model configured for this category
    model = get_model_for_category(category, config_path=config_path)

    # Step 3: Generate the response from the model
    response_text = model.generate(prompt)

    # Step 4: Return combined result
    return {
        "category": category,
        "response": response_text,
        "model_name": model.model_name,
        "backend": model.backend,
    }


class TaskService:
    """Service class for orchestrating task routing and model inference."""

    def __init__(self, config_path: Optional[Union[str, Path]] = None) -> None:
        """Initialize the task service.

        Args:
            config_path: Optional custom path to models.yaml.
        """
        self.config_path = config_path

    def execute(self, prompt: str) -> Dict[str, Any]:
        """Execute task classification and inference for a given user prompt.

        Args:
            prompt: User prompt text.

        Returns:
            Dictionary with category, response, model_name, and backend.
        """
        return process_task(prompt, config_path=self.config_path)
